seotool-database:
  image: mysql:5.5
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=jumbo
    - MYSQL_DATABASE=seo_tool
  volumes:
    - ./environments/vagrant/mysql_data/data:/var/lib/mysql


web:
  build: .
  links:
    - seotool-database
  volumes:
    - ./:/var/www/html
    - ./environments/vagrant/mysql:/etc/mysql/conf.d
  ports:
    - 80:80
